file_format: "1"
id: Release_Recollection
name: Release_Recollection
type: shield
url: https://github.com/eincode0/Release_Recollection.git
requires: [xiao_ble/nrf52840/zmk]
features:
  - keys
  - sensors
